### ISSUE TITLE
please document value returned when nothing is available

### ISSUE THREAD

**Issue by gmabey** [MegaEduX/getch#1]
Thank you for posting this useful function.

Could you please add to the `README` the value of `char` that would be returned if there is nothing ready on stdin?

Thanks!

**Comment by edualm** [comment]
Hey,

This is a super old function that I haven't used in literally ages, but I think it just waits for something to be ready in `stdin` before returning anything.

So, to answer your question, it would hang.

I'm not 100% sure of that, but if you want to test it and confirm I can absolutely add it to the `README`!

Thanks!
